--PUEDE

SELECT * from SYSTEM.HOTEL;

INSERT INTO SYSTEM.HUESPED VALUES(100001,3,'HACKERS',1,1);

UPDATE SYSTEM.MILLA MM
SET MM.cantidad.valor=MM.cantidad.valor*2
WHERE id_milla = 1;

DELETE FROM SYSTEM.PAGO WHERE id_pago = 1;

--NO PUEDE

SELECT * FROM SYSTEM.AVION;

INSERT INTO SYSTEM.USUARIO VALUES(100,'lorem@gmail.com','agente86', DEFAULT, 'lorem', null, 'ipsum',null,'+58123456');

UPDATE SYSTEM.TARJETA_CREDITO
SET banco = 'HACKEADO';

DELETE FROM system.HABITACION;