--PUEDE

SELECT * FROM SYSTEM.carro;

UPDATE SYSTEM.MILLA MM
SET MM.cantidad.valor=MM.cantidad.valor*2;

INSERT INTO SYSTEM.PAGO VALUES(65455, SYSTEM.UNIDAD(800.2618, 'dolar', 'monetaria', 'usd'), SYSTIMESTAMP, SYSTEM.UNIDAD(0, 'millas', 'monetaria', 'milla'), NULL, NULL,2,NULL,1,NULL,NULL);

DELETE FROM SYSTEM.RESERVA_CARRO
WHERE id_reserva_carro = 1;

--NO PUEDE

SELECT * FROM SYSTEM.AVION;

INSERT INTO SYSTEM.MARCA VALUES (14,'CARRITO','aereo');

UPDATE SYSTEM.TARJETA_CREDITO
SET banco = 'HACKEADO';

DELETE FROM SYSTEM.aerolinea;