--PUEDE
SELECT * FROM SYSTEM.AEROLINEA; 
SELECT * FROM SYSTEM.MARCA; 
SELECT * FROM SYSTEM.MODELO; 
SELECT * FROM SYSTEM.AVION; 
SELECT * FROM SYSTEM.PROVEEDOR_CARRO; 
SELECT * FROM SYSTEM.ASIENTO;
SELECT * FROM SYSTEM.DISPONIBILIDAD WHERE id_disponibilidad=78818;
SELECT * FROM SYSTEM.RESERVA_VUELO;

INSERT INTO SYSTEM.MARCA VALUES (13,'HACKEADO','aereo');

UPDATE SYSTEM.RESERVA_VUELO RV
SET RV.reserva_vuelo.monto.valor = RV.reserva_vuelo.monto.valor*2;

DELETE FROM SYSTEM.DISPONIBILIDAD 
WHERE id_disponibilidad=78818;

--NO PUEDE

SELECT * FROM SYSTEM.CARRO; 

DELETE FROM SYSTEM.proveedor_carro; --PUEDE VER MAS NO ELIMINAR

UPDATE SYSTEM.APARTAMENTO
SET nombre = 'hackeado';

DELETE FROM SYSTEM.proveedor_carro;

INSERT INTO SYSTEM.CARACTERISTICA VALUES(56000,'Hackeado','Cocina hackeada',1,null,null);

