--PUEDE
SELECT * FROM SYSTEM.AEROLINEA; 
SELECT * FROM SYSTEM.MARCA; 
SELECT * FROM SYSTEM.MODELO; 
SELECT * FROM SYSTEM.AVION; 
SELECT * FROM SYSTEM.PROVEEDOR_CARRO; 
SELECT * FROM SYSTEM.ASIENTO;
SELECT * FROM SYSTEM.DISPONIBILIDAD WHERE id_disponibilidad=78818;
SELECT * FROM SYSTEM.RESERVA_VUELO;

INSERT INTO MARCA VALUES (id_marca.nextVal,'JEFE','aereo');

UPDATE SYSTEM.RESERVA_VUELO RV
SET RV.reserva_vuelo.monto = RV.reserva_vuelo.monto*2;

DELETE FROM SYSTEM.DISPONIBILIDAD 
WHERE id_disponibilidad=78818;

--NO PUEDE

SELECT * FROM SYSTEM.CARRO; 

DELETE FROM SYSTEM.proveedor_carro;

UPDATE SYSTEM.HABITACION
SET nombre = 'hackeado';

INSERT INTO CARACTERISTICA VALUES(system.id_caracteristica.nextVal,'Hackeado','Cocina hackeada',1,null,null);

