--PUEDE

SELECT * FROM SYSTEM.carro;

INSERT INTO SYSTEM.MARCA VALUES (14,'CARRITO','aereo');

UPDATE SYSTEM.MILLA MM
SET MM.cantidad.valor=MM.cantidad.valor*2;

DELETE FROM SYSTEM.RESERVA_CARRO
WHERE id_reserva_carro = 1;

--NO PUEDE

SELECT * FROM SYSTEM.AVION;

INSERT INTO SYSTEM.USUARIO VALUES(100,'lorem@gmail.com','agente86', DEFAULT, 'lorem', null, 'ipsum',null,'+58123456');

UPDATE SYSTEM.TARJETA_CREDITO
SET banco = 'HACKEADO';

DELETE FROM SYSTEM.aerolinea;