alter session set "_ORACLE_SCRIPT"=true;

CREATE ROLE ADMIN_AEROLINEA; 
CREATE ROLE ADMIN_CARRO;
CREATE ROLE ADMIN_HOTEL;
CREATE ROLE EMPLE_AEROLINEA;
CREATE ROLE EMPLE_CARRO;
CREATE ROLE EMPLE_HOTEL;
CREATE ROLE USER_SYS;

grant create session to ADMIN_AEROLINEA;
grant create session to ADMIN_CARRO;
grant create session to ADMIN_HOTEL;
grant create session to EMPLE_AEROLINEA;
grant create session to EMPLE_CARRO;
grant create session to EMPLE_HOTEL;
grant create session to USER_SYS;

GRANT ALL ON AEROLINEA TO ADMIN_AEROLINEA;
GRANT ALL ON MARCA TO ADMIN_AEROLINEA;
GRANT ALL ON MODELO TO ADMIN_AEROLINEA;
GRANT ALL ON AVION TO ADMIN_AEROLINEA;
GRANT SELECT ON PROVEEDOR_CARRO TO ADMIN_AEROLINEA;
GRANT ALL ON ASIENTO TO ADMIN_AEROLINEA;
GRANT ALL ON AEROPUERTO TO ADMIN_AEROLINEA;
GRANT ALL ON VUELO TO ADMIN_AEROLINEA;
GRANT SELECT ON USUARIO TO ADMIN_AEROLINEA;
GRANT ALL ON DISPONIBILIDAD TO ADMIN_AEROLINEA;
GRANT ALL ON RESERVA_VUELO TO ADMIN_AEROLINEA;
GRANT SELECT ON HOTEL TO ADMIN_AEROLINEA;
GRANT ALL ON ASEGURADORA TO ADMIN_AEROLINEA;
GRANT ALL ON SERVICIO TO ADMIN_AEROLINEA;
GRANT ALL ON SEGURO TO ADMIN_AEROLINEA;
GRANT ALL ON SEGURO_SERVICIO TO ADMIN_AEROLINEA;
GRANT SELECT, UPDATE ON MILLA TO ADMIN_AEROLINEA;
GRANT SELECT ON TARJETA_CREDITO TO ADMIN_AEROLINEA;
GRANT SELECT ON TARJETA_DEBITO TO ADMIN_AEROLINEA;
GRANT ALL ON PAGO TO ADMIN_AEROLINEA;


GRANT SELECT ON AEROLINEA TO ADMIN_CARRO;
GRANT ALL ON MARCA TO ADMIN_CARRO;
GRANT ALL ON MODELO TO ADMIN_CARRO;
GRANT ALL ON PROVEEDOR_CARRO TO ADMIN_CARRO;
GRANT ALL ON CARRO TO ADMIN_CARRO;
GRANT SELECT ON USUARIO TO ADMIN_CARRO;
GRANT SELECT ON RESERVA_VUELO TO ADMIN_CARRO;
GRANT ALL ON RESERVA_CARRO TO ADMIN_CARRO;
GRANT SELECT, UPDATE ON MILLA TO ADMIN_CARRO;
GRANT SELECT ON TARJETA_CREDITO TO ADMIN_CARRO;
GRANT SELECT ON TARJETA_DEBITO TO ADMIN_CARRO;
GRANT ALL ON PAGO TO ADMIN_CARRO;

GRANT SELECT ON AEROLINEA TO ADMIN_HOTEL;
GRANT SELECT ON USUARIO TO ADMIN_HOTEL;
GRANT SELECT ON RESERVA_VUELO TO ADMIN_HOTEL;
GRANT ALL ON HOTEL TO ADMIN_HOTEL;
GRANT ALL ON HABITACION TO ADMIN_HOTEL;
GRANT ALL ON APARTAMENTO TO ADMIN_HOTEL;
GRANT ALL ON CARACTERISTICA TO ADMIN_HOTEL;
GRANT ALL ON RESERVA_ESTANCIA TO ADMIN_HOTEL;
GRANT ALL ON HUESPED TO ADMIN_HOTEL;
GRANT SELECT, UPDATE ON MILLA TO ADMIN_HOTEL;
GRANT SELECT ON TARJETA_CREDITO TO ADMIN_HOTEL;
GRANT SELECT ON TARJETA_DEBITO TO ADMIN_HOTEL;
GRANT ALL ON PAGO TO ADMIN_HOTEL;

GRANT SELECT ON AEROLINEA TO EMPLE_AEROLINEA;
GRANT SELECT ON MARCA TO EMPLE_AEROLINEA;
GRANT SELECT ON MODELO TO EMPLE_AEROLINEA;
GRANT SELECT ON AVION TO EMPLE_AEROLINEA;
GRANT SELECT ON PROVEEDOR_CARRO TO EMPLE_AEROLINEA;
GRANT SELECT, UPDATE ON ASIENTO TO EMPLE_AEROLINEA;
GRANT SELECT, UPDATE ON AEROPUERTO TO EMPLE_AEROLINEA;
GRANT SELECT, UPDATE ON VUELO TO EMPLE_AEROLINEA;
GRANT SELECT ON USUARIO TO EMPLE_AEROLINEA;
GRANT ALL ON DISPONIBILIDAD TO EMPLE_AEROLINEA;
GRANT ALL ON RESERVA_VUELO TO EMPLE_AEROLINEA;
GRANT SELECT ON HOTEL TO EMPLE_AEROLINEA;
GRANT SELECT, UPDATE ON ASEGURADORA TO EMPLE_AEROLINEA;
GRANT SELECT, UPDATE ON SERVICIO TO EMPLE_AEROLINEA;
GRANT ALL ON SEGURO TO EMPLE_AEROLINEA;
GRANT ALL ON SEGURO_SERVICIO TO EMPLE_AEROLINEA;
GRANT SELECT, UPDATE ON MILLA TO EMPLE_AEROLINEA;
GRANT SELECT ON TARJETA_CREDITO TO EMPLE_AEROLINEA;
GRANT SELECT ON TARJETA_DEBITO TO EMPLE_AEROLINEA;
GRANT ALL ON PAGO TO EMPLE_AEROLINEA;


GRANT SELECT ON AEROLINEA TO EMPLE_CARRO;
GRANT SELECT ON MARCA TO EMPLE_CARRO;
GRANT SELECT ON MODELO TO EMPLE_CARRO;
GRANT SELECT ON PROVEEDOR_CARRO TO EMPLE_CARRO;
GRANT SELECT ON CARRO TO EMPLE_CARRO;
GRANT SELECT ON USUARIO TO EMPLE_CARRO;
GRANT SELECT ON RESERVA_VUELO TO EMPLE_CARRO;
GRANT ALL ON RESERVA_CARRO TO EMPLE_CARRO;
GRANT SELECT, UPDATE ON MILLA TO EMPLE_CARRO;
GRANT SELECT ON TARJETA_CREDITO TO EMPLE_CARRO;
GRANT SELECT ON TARJETA_DEBITO TO EMPLE_CARRO;
GRANT ALL ON PAGO TO EMPLE_CARRO;

GRANT SELECT ON AEROLINEA TO EMPLE_HOTEL;
GRANT SELECT ON USUARIO TO EMPLE_HOTEL;
GRANT SELECT ON RESERVA_VUELO TO EMPLE_HOTEL;
GRANT SELECT ON HOTEL TO EMPLE_HOTEL;
GRANT SELECT, UPDATE ON HABITACION TO EMPLE_HOTEL;
GRANT SELECT, UPDATE ON APARTAMENTO TO EMPLE_HOTEL;
GRANT SELECT, UPDATE ON CARACTERISTICA TO EMPLE_HOTEL;
GRANT ALL ON RESERVA_ESTANCIA TO EMPLE_HOTEL;
GRANT ALL ON HUESPED TO EMPLE_HOTEL;
GRANT SELECT, UPDATE ON MILLA TO EMPLE_HOTEL;
GRANT SELECT ON TARJETA_CREDITO TO EMPLE_HOTEL;
GRANT SELECT ON TARJETA_DEBITO TO EMPLE_HOTEL;
GRANT ALL ON PAGO TO EMPLE_HOTEL;

GRANT SELECT ON AEROLINEA TO USER_SYS;
GRANT SELECT ON MARCA TO USER_SYS;
GRANT SELECT ON MODELO TO USER_SYS;
GRANT SELECT ON AVION TO USER_SYS;
GRANT SELECT ON PROVEEDOR_CARRO TO USER_SYS;
GRANT SELECT ON CARRO TO USER_SYS;
GRANT SELECT ON ASIENTO TO USER_SYS;
GRANT SELECT ON AEROPUERTO TO USER_SYS;
GRANT SELECT ON VUELO TO USER_SYS;
GRANT ALL ON USUARIO TO USER_SYS;
GRANT SELECT ON DISPONIBILIDAD TO USER_SYS;
GRANT ALL ON RESERVA_VUELO TO USER_SYS;
GRANT ALL ON RESERVA_CARRO TO USER_SYS;
GRANT SELECT ON HOTEL TO USER_SYS;
GRANT SELECT ON HABITACION TO USER_SYS;
GRANT SELECT ON APARTAMENTO TO USER_SYS;
GRANT SELECT ON CARACTERISTICA TO USER_SYS;
GRANT ALL ON RESERVA_ESTANCIA TO USER_SYS;
GRANT ALL ON HUESPED TO USER_SYS;
GRANT SELECT ON ASEGURADORA TO USER_SYS;
GRANT SELECT ON SERVICIO TO USER_SYS;
GRANT ALL ON SEGURO TO USER_SYS;
GRANT ALL ON SEGURO_SERVICIO TO USER_SYS;
GRANT SELECT,UPDATE ON MILLA TO USER_SYS;
GRANT ALL ON TARJETA_CREDITO TO USER_SYS;
GRANT ALL ON TARJETA_DEBITO TO USER_SYS;
GRANT ALL ON PAGO TO USER_SYS;

CREATE USER jefe_aerolinea IDENTIFIED BY jefe_aerolinea;
CREATE USER jefe_carro IDENTIFIED BY jefe_carro;
CREATE USER jefe_hotel IDENTIFIED BY jefe_hotel;
CREATE USER empleado_aerolinea IDENTIFIED BY empleado_aerolinea;
CREATE USER empleado_carro IDENTIFIED BY empleado_carro;
CREATE USER empleado_hotel IDENTIFIED BY empleado_hotel;
CREATE USER armen IDENTIFIED BY armen;

GRANT ADMIN_AEROLINEA TO jefe_aerolinea;
GRANT ADMIN_CARRO TO jefe_carro;
GRANT ADMIN_HOTEL TO jefe_hotel;
GRANT EMPLE_AEROLINEA TO empleado_aerolinea;
GRANT EMPLE_CARRO TO empleado_carro;
GRANT EMPLE_HOTEL TO empleado_hotel;
GRANT USER_SYS TO armen;

--NUEVOOOOOOOOOOOOO

GRANT ALL ON UNIDAD TO ADMIN_AEROLINEA;
GRANT ALL ON UNIDAD TO ADMIN_CARRO;
GRANT ALL ON UNIDAD TO ADMIN_HOTEL;
GRANT ALL ON UNIDAD TO EMPLE_AEROLINEA;
GRANT ALL ON UNIDAD TO EMPLE_CARRO;
GRANT ALL ON UNIDAD TO EMPLE_HOTEL;
GRANT ALL ON UNIDAD TO USER_SYS;

GRANT ALL ON LUGAR TO ADMIN_AEROLINEA;
GRANT ALL ON LUGAR TO ADMIN_CARRO;
GRANT ALL ON LUGAR TO ADMIN_HOTEL;
GRANT ALL ON LUGAR TO EMPLE_AEROLINEA;
GRANT ALL ON LUGAR TO EMPLE_CARRO;
GRANT ALL ON LUGAR TO EMPLE_HOTEL;
GRANT ALL ON LUGAR TO USER_SYS;

GRANT ALL ON RESERVA TO ADMIN_AEROLINEA;
GRANT ALL ON RESERVA TO ADMIN_CARRO;
GRANT ALL ON RESERVA TO ADMIN_HOTEL;
GRANT ALL ON RESERVA TO EMPLE_AEROLINEA;
GRANT ALL ON RESERVA TO EMPLE_CARRO;
GRANT ALL ON RESERVA TO EMPLE_HOTEL;
GRANT ALL ON RESERVA TO USER_SYS;

